import "./globals.css";
import StoreProvider from "./  StoreProvider";
import { Hind_Siliguri } from "next/font/google";
import { Metadata } from "next";

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Test Dashboard for SkillUpper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${hindSiliguri.className} antialiased`}>
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
